root: true
env:
  commonjs: true
  node: true
  es2021: true
extends:
  - "eslint:recommended"
  - "prettier"
parserOptions:
  ecmaVersion: 12
  sourceType: module
overrides:
  - files: [src/script/**/*.js]
    globals:
      Swiper: true
  - files: ["*.astro"]
    parser: eslint-plugin-astro
    extends:
      - plugin:astro/recommended
  - files: ["**/*.{ts,tsx}"]
    parser: "@typescript-eslint/parser"
    extends:
      - plugin:@typescript-eslint/recommended
