root: true
env:
  commonjs: true
  node: true
extends:
  - "eslint:recommended"
  - "prettier"
parserOptions:
  ecmaVersion: 12
overrides:
  - files: [src/script/**/*.js]
    globals:
      Swiper: true
