
name: Build Pages
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    name: Build Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Touch secret env
        run: |
          touch .env
          echo ${{ secrets.XKEY }} >> .env
          
      - name: Install yarn and dependencies
        run: yarn
        
      - name: Build static pages
        run: yarn build
