name: ビルドのテスト

on:
  push:
    branches: [master]
  repository_dispatch:
    types: [foo, orange]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Touch secret env ${{ secrets.XKEY }}
        run: |
          touch .env
          echo "XKEY=${{ secrets.XKEY }}" >> .env
      - run: pnpm
      - run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
