name: ビルドのテスト

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Touch secret env
        run: |
          touch .env
          echo ${{ secrets.XKEY }} >> .env
      - run: yarn
      - run: yarn build
