name: Format
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --check-files --frozen-lockfile --non-interactive
      - id: format
        run: |
          pnpm format
          echo "::set-output name=status::$(git status --porcelain)"
      - if: steps.format.outputs.status != ''
        run: |
          git -c "user.name=${{ github.actor }}" -c "user.email=${{ github.actor }}@users.noreply.github.com" commit -a -m "bot: format"
          git push origin HEAD
